---
title: "HER2 mouse ssGSEA"
output:
  html_document:
    code_folding: show
    toc: true
    toc_depth: 2
    toc_float: true
    theme: cosmo
    highlight: tango
---

# load library and data

```{r echo=FALSE}
.libPaths(c("/home/aahn/R/x86_64-pc-linux-gnu-library/4.2", "/config/binaries/R/4.2.0/R_libraries", "/config/binaries/R/4.2.0/lib64/R/library"))
```

```{r echo=FALSE, results=FALSE, message=FALSE}
library(tidyverse)
library(ggrepel)
library(ggpubr)
library(cowplot)
library(DESeq2)
library(DT)
library(ggplot2)
library(RColorBrewer)
library(biomaRt)
library(ggsci)
library(pheatmap)
library(msigdbr)
library(GSVA)
library(ComplexHeatmap)
library(circlize)
```

```{r echo=FALSE}
load("/researchers/krutika.ambani/Goel_lab_members/Cath_Dietrich/230720_ABEMA_ARC_COMBO_VEH_primary_mouse_tumour_upfront/R_analysis/1.QC_prep/data/RData/prep.RData")
```

# subset samples

# ssGSEA

```{r message=FALSE, results=FALSE}
# make senescence_markers_df into a list
# mmust be an simpler way to do this ...
GSEA.list <- vector(mode = "list", length = length(senescence_markers_df$gs_name %>% unique()))
for (i in 1:length(senescence_markers_df$gs_name %>% unique())) {
  GSEA.list[[i]] <- senescence_markers_df %>%
    filter(gs_name == unique(senescence_markers_df$gs_name)[i]) %>%
    .$gene_symbol
}
names(GSEA.list) <- senescence_markers_df$gs_name %>% unique()

GSEA.list$Jochems <- NULL


Senscore_ssGSEA <- gsva(expr = norm_mat_symbol_log, gset.idx.list = GSEA.list, mx.diff = TRUE, verbose = TRUE, parallel.sz = 2, method = "ssgsea") %>% data.frame()
```


```{r}
index_up <- c(1, 3, 5, 6)
heatmap_mat <- Senscore_ssGSEA[index_up, ]

scaled.mat <- t(scale(t(heatmap_mat)))

##### ----------------------------------------------------------------------------------------------------
# column colors
# incyclix_col <- c("#872464", "#0070B9", "#FFC541", "#00A8E3")
# column_color_treatment <- col_npg5[1:4]
column_color_treatment <- c("#00A8E3", "#872464", "#FFC541", "#0070B9")
# column_color_time <- ggsci::pal_simpsons()(8)[1:5]
# column_color_time <- carto_pal(5, "SunsetDark")
# column_color_time <- carto_pal(13, "Sunset")[c(1,4,7,10,13)]

names(column_color_treatment) <- unique(sample_information$treatment)
# names(column_color_time) <- sample_information$time %>% factor %>% levels

anno_colors <- list(treatment = column_color_treatment)
#                    time = column_color_time)
# column annotations
column_ha <- HeatmapAnnotation(
  mean = anno_barplot(colMeans(scaled.mat), height = unit(2, "cm")),
  treatment = sample_information$treatment,
  # time = sample_information$time,
  col = anno_colors
)

column_ha_boxplot <- HeatmapAnnotation(
  boxplot = anno_boxplot(scaled.mat, height = unit(2, "cm")),
  treatment = sample_information$treatment,
  # time = sample_information$time,
  col = anno_colors
)

# column split
column_split <- sample_information$treatment
##### ----------------------------------------------------------------------------------------------------
# cell colors
col.pan <- colorRampPalette(c("black", "dodgerblue3", "white", "orange", "red"))(100)
##### ----------------------------------------------------------------------------------------------------
# make heatmap
Heatmap(scaled.mat,
  name = "z-score",
  col = col.pan,
  top_annotation = column_ha,
  cluster_columns = FALSE,
  row_km = 1, show_row_names = TRUE, row_names_gp = gpar(fontsize = 12),
  column_split = sample_information$treatment
)


Heatmap(scaled.mat,
  name = "z-score",
  col = col.pan,
  top_annotation = column_ha_boxplot,
  cluster_columns = FALSE,
  row_km = 1, show_row_names = TRUE, row_names_gp = gpar(fontsize = 12),
  column_split = sample_information$treatment
)

# make_heatmap_symbol_CHM(filter(h_gene_sets, gs_name == "HALLMARK_E2F_TARGETS")$gene_symbol, kmeansrows_number = 1)
```



```{r eval=FALSE}
save_pdf_dir <- "/researchers/krutika.ambani/Goel_lab_members/Cath_Dietrich/230720_ABEMA_ARC_COMBO_VEH_primary_mouse_tumour_upfront/R_analysis/paper_figures/figures_output"

setwd(save_pdf_dir)

pdf("HER2mouse_overcomeresist_ssGSEAsenscore_heatmap_1.pdf",
  width = 8, # 5 x 300 pixels
  height = 6
) # 300 pixels per inch)        # smaller font size


Heatmap(scaled.mat,
  name = "z-score",
  col = col.pan,
  top_annotation = column_ha,
  cluster_columns = FALSE,
  row_km = 1, show_row_names = TRUE, row_names_gp = gpar(fontsize = 12),
  column_split = sample_information$treatment
)


dev.off()


pdf("HER2mouse_overcomeresist_ssGSEAsenscore_heatmap_2.pdf",
  width = 8, # 5 x 300 pixels
  height = 6
) # 300 pixels per inch)        # smaller font size


Heatmap(scaled.mat,
  name = "z-score",
  col = col.pan,
  top_annotation = column_ha_boxplot,
  cluster_columns = FALSE,
  row_km = 1, show_row_names = TRUE, row_names_gp = gpar(fontsize = 12),
  column_split = sample_information$treatment
)


dev.off()
```

