---
title: "MCF7 T47D senescence score barplot"
output:
  html_document:
    code_folding: show
    toc: true
    toc_depth: 2
    toc_float: true
    theme: cosmo
    highlight: tango
---

# load library

```{r echo=FALSE}
.libPaths(c("/home/aahn/R/x86_64-pc-linux-gnu-library/4.2", "/config/binaries/R/4.2.0/R_libraries", "/config/binaries/R/4.2.0/lib64/R/library"))
```

```{r include = FALSE, message=FALSE}
# load library

library(tidyverse)
library(ggrepel)
library(ggpubr)
library(cowplot)
library(DESeq2)
library(DT)
library(ggplot2)
library(RColorBrewer)
library(biomaRt)
library(ggsci)
library(pheatmap)
library(gplots)
library(ggdendro)
library(edgeR)
library(clusterProfiler)
library(ComplexHeatmap)
library(UpSetR)
library(GSVA)
library(ggprism)
```


```{r echo=FALSE}
# from preparation file
# load(file = "/researchers/krutika.ambani/Goel_lab_members/Cath_Dietrich/220801_MCF7M_T47D_LY_LYFR/R_analysis/MCF7M/antonioahn/preparation/data/preparation.RData")
load(file = "/researchers/krutika.ambani/Goel_lab_members/Cath_Dietrich/220801_MCF7M_T47D_LY_LYFR/R_analysis/MCF7M_T47D_combined_AA/preparation/data/preparation.RData")

load("/researchers/antonio.ahn/general/R/Download_resources/RData/mart_apr2019.RData")
load("/researchers/antonio.ahn/general/R/Download_resources/RData/mart_aug2020.RData")
```



# ssGSEA senscore

```{r results=FALSE, echo=FALSE}
senescence_markers_df <- read.csv("/researchers/antonio.ahn/resources/Senescence_gene_expression_markers/Senescopedia_Jochems_ReneBernard_gene_expression_markers/Senescence_geneexpression_markers.csv")
```

```{r}
senescence_markers_df <- senescence_markers_df %>%
  gather(key = "gs_name", value = "gene_symbol") %>%
  filter(gene_symbol != "")
```

# ssGSEA

```{r}
norm_mat_list <- norm_mat_list %>% lapply(function(x) {
  x %>%
    data.frame() %>%
    dplyr::select(contains(c("_PAR_DMSO_", "_PAR_LY_", "_LYR_DMSO_", "_LYR_ARC_", "_LYFR_DMSO_", "_LYFR_ARC_")))
})
```

```{r message=FALSE, results=FALSE}
# make senescence_markers_df into a list
# mmust be an simpler way to do this ...
GSEA.list <- vector(mode = "list", length = length(senescence_markers_df$gs_name %>% unique()))
for (i in 1:length(senescence_markers_df$gs_name %>% unique())) {
  GSEA.list[[i]] <- senescence_markers_df %>%
    filter(gs_name == unique(senescence_markers_df$gs_name)[i]) %>%
    .$gene_symbol
}
names(GSEA.list) <- senescence_markers_df$gs_name %>% unique()

GSEA.list$Jochems <- NULL

Senscore_ssGSEA <- vector(mode = "list", length = length(norm_mat_list))
for (i in 1:length(Senscore_ssGSEA)) {
  Senscore_ssGSEA[[i]] <- gsva(expr = as.matrix(norm_mat_list[[i]]), gset.idx.list = GSEA.list, mx.diff = TRUE, verbose = TRUE, parallel.sz = 2, method = "ssgsea") %>% data.frame()
}

names(Senscore_ssGSEA) <- names(norm_mat_list)
```

# MCF7M

```{r}
index_up <- c(1, 3, 5, 6)
```

```{r}
Senscore_ssGSEA_MCF7M <- Senscore_ssGSEA$MCF7M

Senscore_ssGSEA_MCF7M_ggplot <- Senscore_ssGSEA_MCF7M[index_up, ] %>% as_tibble(rownames = "group")
Senscore_ssGSEA_MCF7M_ggplot <- gather(Senscore_ssGSEA_MCF7M_ggplot, key = names, value = value, -group)
Senscore_ssGSEA_MCF7M_ggplot <- Senscore_ssGSEA_MCF7M_ggplot %>% separate(names, c("cellline", "resist", "treatment", "replicate"), remove = FALSE, sep = "_")

Senscore_ssGSEA_MCF7M_ggplot <- Senscore_ssGSEA_MCF7M_ggplot %>% unite(col = resist_treat, c("resist", "treatment"), remove = FALSE)

Senscore_ssGSEA_MCF7M_ggplot$resist_treat <- Senscore_ssGSEA_MCF7M_ggplot$resist_treat %>% factor(levels = c("PAR_DMSO", "PAR_LY", "LYR_DMSO", "LYR_ARC", "LYFR_DMSO", "LYFR_ARC"))
```

```{r}
my_comparisons <- list(
  c("PAR_DMSO", "PAR_LY"),
  c("LYR_DMSO", "LYR_ARC"),
  c("LYFR_DMSO", "LYFR_ARC")
)

incyclix_col <- c("#872464", "#0070B9", "#FFC541", "#00A8E3")

boxplot_col <- c(
  "PAR_DMSO" = "#00A8E3",
  "PAR_LY" = "#872464",
  "LYR_DMSO" = "#0070B9",
  "LYR_ARC" = "#FFC541",
  "LYFR_DMSO" = "#0070B9",
  "LYFR_ARC" = "#FFC541"
)

Senscore_ssGSEA_MCF7M_ggplot %>% filter(group == "Casella_UP")
# t.test(x = c( 0.1638525, 0.1832479, 0.1600299), y = c(0.3376492, 0.3420807, 0.3377224) )
Senscore_ssGSEA_MCF7M_ggplot <- Senscore_ssGSEA_MCF7M_ggplot %>%
  group_by(group, resist) %>%
  summarise(
    names = names,
    treatment = treatment,
    resist = resist,
    resist_treat = resist_treat,
    value = value,
    replicate = replicate,
    relative_value = value / abs(mean(value[treatment == "DMSO"]))
  )



a1 <- Senscore_ssGSEA_MCF7M_ggplot %>%
  ggplot(aes(x = resist_treat, y = relative_value)) +
  # geom_boxplot(lwd=1, show.legend=FALSE) +
  # geom_bar(stat="identity",
  # position=position_dodge()) +
  # geom_errorbar(aes(ymin=len-sd, ymax=len+sd), width=.2,
  # position=position_dodge(.9))  +
  # geom_errorbar() +
  geom_bar(aes(fill = resist_treat),
    stat = "summary", fun = "mean",
    position = position_dodge(), width = 1, show.legend = FALSE
  ) +
  # stat_summary(fun=mean, geom="point", color="red") +
  scale_fill_manual(values = boxplot_col) +
  stat_compare_means(comparisons = my_comparisons, label = "p.format", method = "t.test", bracket.size = 1.5, label.y = c(4, 4, 4)) +
  geom_jitter(aes(col = resist_treat), size = 0.20, color = "black", stroke = 3) +
  stat_summary(
    fun.data = mean_sdl, fun.args = list(mult = 1),
    geom = "errorbar", color = "black", width = 0.5, linewidth = 0.5
  ) +
  ylab("relative ssGSEA score") +
  ggtitle("MCF7M") +
  facet_grid(. ~ group) +
  theme_prism() +
  theme(
    axis.text.y = element_text(color = "black", size = 15),
    axis.text.x = element_text(color = "black", size = 15, angle = 45, hjust = 1, vjust = 1),
    axis.title.y = element_text(color = "black", size = 20),
    axis.title.x = element_blank(),
    strip.text.x = element_text(size = 15)
  )

a1
```


```{r eval=FALSE}
save_pdf_dir <- "/researchers/krutika.ambani/Goel_lab_members/Cath_Dietrich/220801_MCF7M_T47D_LY_LYFR/R_analysis/MCF7M_T47D_combined_AA/1.overcome_resistance/paper_figures/figures_output"

setwd(save_pdf_dir)

pdf("overcomeresist_MCF7M_ssGSEA_senscore.pdf",
  width = 15, # 5 x 300 pixels
  height = 6
) # 300 pixels per inch)        # smaller font size

a1

dev.off()
```



# T47D

```{r}
index_up <- c(1, 3, 5, 6)
```

```{r}
Senscore_ssGSEA_T47D <- Senscore_ssGSEA$T47D

Senscore_ssGSEA_T47D_ggplot <- Senscore_ssGSEA_T47D[index_up, ] %>% as_tibble(rownames = "group")
Senscore_ssGSEA_T47D_ggplot <- gather(Senscore_ssGSEA_T47D_ggplot, key = names, value = value, -group)
Senscore_ssGSEA_T47D_ggplot <- Senscore_ssGSEA_T47D_ggplot %>% separate(names, c("cellline", "resist", "treatment", "replicate"), remove = FALSE, sep = "_")

Senscore_ssGSEA_T47D_ggplot <- Senscore_ssGSEA_T47D_ggplot %>% unite(col = resist_treat, c("resist", "treatment"), remove = FALSE)

Senscore_ssGSEA_T47D_ggplot$resist_treat <- Senscore_ssGSEA_T47D_ggplot$resist_treat %>% factor(levels = c("PAR_DMSO", "PAR_LY", "LYR_DMSO", "LYR_ARC", "LYFR_DMSO", "LYFR_ARC"))
```

```{r}
my_comparisons <- list(
  c("PAR_DMSO", "PAR_LY"),
  c("LYR_DMSO", "LYR_ARC"),
  c("LYFR_DMSO", "LYFR_ARC")
)

incyclix_col <- c("#872464", "#0070B9", "#FFC541", "#00A8E3")

boxplot_col <- c(
  "PAR_DMSO" = "#00A8E3",
  "PAR_LY" = "#872464",
  "LYR_DMSO" = "#0070B9",
  "LYR_ARC" = "#FFC541",
  "LYFR_DMSO" = "#0070B9",
  "LYFR_ARC" = "#FFC541"
)

Senscore_ssGSEA_T47D_ggplot %>% filter(group == "Casella_UP")
# t.test(x = c( 0.1638525, 0.1832479, 0.1600299), y = c(0.3376492, 0.3420807, 0.3377224) )
Senscore_ssGSEA_T47D_ggplot <- Senscore_ssGSEA_T47D_ggplot %>%
  group_by(group, resist) %>%
  summarise(
    names = names,
    treatment = treatment,
    resist = resist,
    resist_treat = resist_treat,
    value = value,
    replicate = replicate,
    relative_value = value / abs(mean(value[treatment == "DMSO"]))
  )



a1 <- Senscore_ssGSEA_T47D_ggplot %>%
  ggplot(aes(x = resist_treat, y = relative_value)) +
  # geom_boxplot(lwd=1, show.legend=FALSE) +
  # geom_bar(stat="identity",
  # position=position_dodge()) +
  # geom_errorbar(aes(ymin=len-sd, ymax=len+sd), width=.2,
  # position=position_dodge(.9))  +
  # geom_errorbar() +
  geom_bar(aes(fill = resist_treat),
    stat = "summary", fun = "mean",
    position = position_dodge(), width = 1, show.legend = FALSE
  ) +
  # stat_summary(fun=mean, geom="point", color="red") +
  scale_fill_manual(values = boxplot_col) +
  stat_compare_means(comparisons = my_comparisons, label = "p.format", method = "t.test", bracket.size = 1.5, label.y = c(4, 4, 4)) +
  geom_jitter(aes(col = resist_treat), size = 0.20, color = "black", stroke = 3) +
  stat_summary(
    fun.data = mean_sdl, fun.args = list(mult = 1),
    geom = "errorbar", color = "black", width = 0.5, linewidth = 0.5
  ) +
  ylab("relative ssGSEA score") +
  ggtitle("T47D") +
  facet_grid(. ~ group) +
  theme_prism() +
  theme(
    axis.text.y = element_text(color = "black", size = 15),
    axis.text.x = element_text(color = "black", size = 15, angle = 45, hjust = 1, vjust = 1),
    axis.title.y = element_text(color = "black", size = 20),
    axis.title.x = element_blank(),
    strip.text.x = element_text(size = 15)
  )

a1
```


```{r eval=FALSE}
save_pdf_dir <- "/researchers/krutika.ambani/Goel_lab_members/Cath_Dietrich/220801_MCF7M_T47D_LY_LYFR/R_analysis/MCF7M_T47D_combined_AA/1.overcome_resistance/paper_figures/figures_output"

setwd(save_pdf_dir)

pdf("overcomeresist_T47D_ssGSEA_senscore.pdf",
  width = 15, # 5 x 300 pixels
  height = 6
) # 300 pixels per inch)        # smaller font size

a1

dev.off()
```



# heatmap 

```{r}
Senscore_ssGSEA_MCF7M
index_up <- c(1, 3, 5, 6)
# up
scaled.mat <- t(scale(t(Senscore_ssGSEA$MCF7M[index_up, ])))
samples <- Senscore_ssGSEA$MCF7M %>% colnames()
# make_ssGSEA_MCF7M_hm(scaled.mat, s_interest = samples, gaps_col = c(12,17))
```

# heatmap MCF7M

```{r}
cellline <- "MCF7M"

# genes_input  <- intersect(genes_input, rownames(norm_mat_list[[cellline]]))

sample_information_filt <- sample_information_list[[cellline]] %>% filter(!resist_treat %in% c("PAR_ARC", "PAR_LY.ARC"))


scaled.mat <- t(scale(t(Senscore_ssGSEA$MCF7M[index_up, ])))
##### ----------------------------------------------------------------------------------------------------
# column colors
# incyclix_col <- c("#872464", "#0070B9", "#FFC541", "#00A8E3")

# column_color_treatment <- col_npg5[1:3]
column_color_treatment <- c("#00A8E3", "#872464", "#FFC541")
# column_color_resistance <- ggsci::pal_simpsons()(8)[1:3]
column_color_resistance <- col_npg5[1:3]

names(column_color_treatment) <- unique(sample_information_filt$treatment)
names(column_color_resistance) <- unique(sample_information_filt$resistance)

anno_colors <- list(
  treatment = column_color_treatment,
  resistance = column_color_resistance
)
# column annotations
column_ha <- HeatmapAnnotation(
  mean = anno_barplot(colMeans(scaled.mat), height = unit(2, "cm")),
  treatment = sample_information_filt$treatment,
  resistance = sample_information_filt$resistance,
  col = anno_colors
)
# column split
column_split <- factor(sample_information_filt$resistance, levels = c("PAR", "LYR", "LYFR"))
##### ----------------------------------------------------------------------------------------------------
# cell colors
col.pan <- colorRampPalette(c("black", "dodgerblue3", "white", "orange", "red"))(100)
##### ----------------------------------------------------------------------------------------------------
# make heatmap
a1 <- Heatmap(scaled.mat,
  name = "z-score",
  col = col.pan,
  top_annotation = column_ha,
  cluster_columns = FALSE, cluster_rows = FALSE,
  row_km = 1, show_row_names = TRUE, row_names_gp = gpar(fontsize = 12),
  column_split = column_split
)

a1
```



# heatmap T47D

```{r}
cellline <- "T47D"

# genes_input  <- intersect(genes_input, rownames(norm_mat_list[[cellline]]))

sample_information_filt <- sample_information_list[[cellline]] %>% filter(!resist_treat %in% c("PAR_ARC", "PAR_LY.ARC"))


scaled.mat <- t(scale(t(Senscore_ssGSEA$T47D[index_up, ])))
##### ----------------------------------------------------------------------------------------------------
# column colors
# incyclix_col <- c("#872464", "#0070B9", "#FFC541", "#00A8E3")

# column_color_treatment <- col_npg5[1:3]
column_color_treatment <- c("#00A8E3", "#872464", "#FFC541")
# column_color_resistance <- ggsci::pal_simpsons()(8)[1:3]
column_color_resistance <- col_npg5[1:3]

names(column_color_treatment) <- unique(sample_information_filt$treatment)
names(column_color_resistance) <- unique(sample_information_filt$resistance)

anno_colors <- list(
  treatment = column_color_treatment,
  resistance = column_color_resistance
)
# column annotations
column_ha <- HeatmapAnnotation(
  mean = anno_barplot(colMeans(scaled.mat), height = unit(2, "cm")),
  treatment = sample_information_filt$treatment,
  resistance = sample_information_filt$resistance,
  col = anno_colors
)
# column split
column_split <- factor(sample_information_filt$resistance, levels = c("PAR", "LYR", "LYFR"))
##### ----------------------------------------------------------------------------------------------------
# cell colors
col.pan <- colorRampPalette(c("black", "dodgerblue3", "white", "orange", "red"))(100)
##### ----------------------------------------------------------------------------------------------------
# make heatmap
a2 <- Heatmap(scaled.mat,
  name = "z-score",
  col = col.pan,
  top_annotation = column_ha,
  cluster_columns = FALSE, cluster_rows = FALSE,
  row_km = 1, show_row_names = TRUE, row_names_gp = gpar(fontsize = 12),
  column_split = column_split
)

a2
```


```{r eval=FALSE}
save_pdf_dir <- "/researchers/krutika.ambani/Goel_lab_members/Cath_Dietrich/220801_MCF7M_T47D_LY_LYFR/R_analysis/MCF7M_T47D_combined_AA/1.overcome_resistance/paper_figures/figures_output"

setwd(save_pdf_dir)

pdf("overcomeresist_MCF7M_ssGSEA_senscore_heatmap.pdf",
  width = 8, # 5 x 300 pixels
  height = 6
) # 300 pixels per inch)        # smaller font size


a1

dev.off()


pdf("overcomeresist_T47D_ssGSEA_senscore_heatmap.pdf",
  width = 8, # 5 x 300 pixels
  height = 6
) # 300 pixels per inch)        # smaller font size


a2

dev.off()
```

