---
title: "MCF7 T47D E2F heatmap"
output:
  html_document:
    code_folding: show
    toc: true
    toc_depth: 2
    toc_float: true
    theme: cosmo
    highlight: tango
---

# load library

```{r echo=FALSE}
.libPaths(c("/home/aahn/R/x86_64-pc-linux-gnu-library/4.2", "/config/binaries/R/4.2.0/R_libraries", "/config/binaries/R/4.2.0/lib64/R/library"))
```

```{r include = FALSE, message=FALSE}
# load library

library(tidyverse)
library(DESeq2)
library(DT)
library(ggplot2)
library(RColorBrewer)
library(biomaRt)
library(pheatmap)
library(gplots)
library(ComplexHeatmap)
library(msigdbr)
library(ggpubr)
```


```{r echo=FALSE}
# from preparation file
load(file = "/researchers/krutika.ambani/Goel_lab_members/Cath_Dietrich/220801_MCF7M_T47D_LY_LYFR/R_analysis/MCF7M/antonioahn/preparation/data/preparation.RData")
```

# genesets of interest

```{r}
h_gene_sets <- msigdbr(species = "Homo sapiens", category = "H")
h_list <- split(x = h_gene_sets$gene_symbol, f = h_gene_sets$gs_name)

c5_gene_sets <- msigdbr(species = "Homo sapiens", category = "C5")
c5_list <- split(x = c5_gene_sets$gene_symbol, f = c5_gene_sets$gs_name)
```


# heatmap

```{r}
incyclix_col <- c("#872464", "#0070B9", "#FFC541", "#00A8E3")
# show_col(incyclix_col)
boxplot_col <- c(
  "PAR_DMSO" = "#0070B9",
  "PAR_LY" = "#872464",
  "LYR_DMSO" = "#FFC541",
  "LYFR_DMSO" = "#00A8E3"
)



make_heatmap_symbol_CHM <- function(genes_input, cellline,
                                    turnon_rownames = FALSE, rownames_size = 7,
                                    turnon_clusterrows = TRUE, show_barplot = FALSE,
                                    kmeansrows_number = 1) {
  # only get the genes that interesct between genes_input and the genes in the normalised matrix
  genes_input <- intersect(genes_input, rownames(norm_mat_list[[cellline]]))

  sample_information_filt <- sample_information_list[[cellline]] %>% filter(resistance %in% c("PAR"))
  samples_interest <- sample_information_filt$name
  heatmap_mat <- norm_mat_list[[cellline]][genes_input, samples_interest]
  # take out any rows with all zero's in the rows. This sometimes happens because when i only select out the PAR group, all zeros but its in the matrix because in the LYFR it is expressed. These are quite interesting... SASP genes that are not expressed at PAR but only expressed in LYFR. I wonder if these are expressed at PAR treated with LY + Fulv. shouldn't be? cuz Fulv brings most things down ...
  index <- apply(heatmap_mat, 1, function(row) all(row == 0))
  heatmap_mat <- heatmap_mat[!index, ]
  # generate z-score
  scaled.mat <- t(scale(t(heatmap_mat)))
  ##### ----------------------------------------------------------------------------------------------------
  # column colors
  # incyclix_col <- c("#872464", , "#FFC541", "#00A8E3")

  # column_color_treatment <- col_npg5[1:3]
  column_color_treatment <- c("#00A8E3", "#872464", "#FFC541", "#0070B9")
  # column_color_resistance <- ggsci::pal_simpsons()(8)[1:3]
  # column_color_resistance <- col_npg5[1:3]

  names(column_color_treatment) <- unique(sample_information_filt$treatment)
  # names(column_color_resistance) <- unique(sample_information_filt$resistance)

  anno_colors <- list(treatment = column_color_treatment)
  # resistance = column_color_resistance)
  # column annotations
  column_ha <- HeatmapAnnotation(
    mean = anno_barplot(colMeans(scaled.mat), height = unit(2, "cm")),
    treatment = sample_information_filt$treatment,
    # resistance = sample_information_filt$resistance,
    col = anno_colors
  )
  # column split
  column_split <- factor(sample_information_filt$treatment, levels = c("DMSO", "LY", "ARC", "LY.ARC"))
  ##### ----------------------------------------------------------------------------------------------------
  # cell colors
  col.pan <- colorRampPalette(c("black", "dodgerblue3", "white", "orange", "red"))(100)
  ##### ----------------------------------------------------------------------------------------------------
  # make heatmap
  Heatmap(scaled.mat,
    name = "z-score",
    col = col.pan,
    top_annotation = column_ha,
    cluster_columns = FALSE,
    row_km = kmeansrows_number, show_row_names = turnon_rownames, row_names_gp = gpar(fontsize = rownames_size),
    column_split = column_split
  )
}
```

```{r}
genes_input <- filter(h_gene_sets, gs_name == "HALLMARK_E2F_TARGETS")$gene_symbol

make_heatmap_symbol_CHM(genes_input,
  cellline = "MCF7M",
  kmeansrows_number = 1
)


make_heatmap_symbol_CHM(genes_input,
  cellline = "T47D",
  kmeansrows_number = 1
)
```


```{r eval=FALSE}
save_pdf_dir <- "/researchers/krutika.ambani/Goel_lab_members/Cath_Dietrich/220801_MCF7M_T47D_LY_LYFR/R_analysis/MCF7M_T47D_combined_AA/2.prevent_resistance/paper_figures/figures_output"

setwd(save_pdf_dir)

pdf("preventresist_MCF7M_E2Ftarget_heatmap.pdf",
  width = 8, # 5 x 300 pixels
  height = 6
) # 300 pixels per inch)        # smaller font size


make_heatmap_symbol_CHM(genes_input,
  cellline = "MCF7M",
  kmeansrows_number = 1
)

dev.off()


pdf("preventresist_T47D_E2Ftarget_heatmap.pdf",
  width = 8, # 5 x 300 pixels
  height = 6
) # 300 pixels per inch)        # smaller font size


make_heatmap_symbol_CHM(genes_input,
  cellline = "T47D",
  kmeansrows_number = 1
)


dev.off()
```


